---
ID: "f6cd0e13-6119-48b2-b01f-086942d17c84"
Parent: "0fd6cb63-8e53-4629-8c8c-fc519d1b67f7"
Template: "0fd6cb63-8e53-4629-8c8c-fc519d1b67f7"
Path: /sitecore/templates/Project/Training Final/Pages/Search Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210416T165554Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8367a2f9-ae8f-4cc8-b12b-55695568c32e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210416T165840Z
