---
ID: "8f07f69b-3c9a-4065-b8bb-4684ed18384d"
Parent: "6c4f1a01-ecd2-5d93-99c8-2a400402329a"
Template: "82dc562c-e094-5467-bd98-7ff216e0d866"
Path: "/sitecore/content/JSS Sites/traineeA/home/training-page"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{3C2B81C4-7E77-4DD4-AA5B-5997F91D5B91}"
              p:after="*[1=2]"
              s:ds="{6DB0C6D8-A1AF-49A0-A88C-3F9AD941A8FF}"
              s:id="{CBE3D3FF-B80C-4C5D-A9E2-8EF9201208E5}"
              s:par=""
              s:ph="jss-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210414T150845Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{AF32C98B-C828-42AF-A649-74C1DE3303FB}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "87310daf-19bb-45a0-a706-8cff5d650c8f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210414T151904Z
