---
ID: "cf60c606-4cf2-4e81-b83e-c2a9df25219f"
Parent: "df5c9b21-910e-4dc7-991e-b7de8d12352a"
Template: "82dc562c-e094-5467-bd98-7ff216e0d866"
Path: "/sitecore/content/JSS Sites/Training Start/home/training-page"
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{C0C028D5-215A-4925-9B3C-A2726157C5AA}"
              p:after="*[1=2]"
              s:ds="{FB4A0F23-FAFD-4B62-9BBF-5A98B572A890}"
              s:id="{7ED7F385-C97E-45E4-A5E5-0CE68F294EB2}"
              s:par=""
              s:ph="jss-main"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "0e1e2d46-2bf4-5935-a503-b64ef6da7301"
      Hint: pageTitle
      Value: Training Page
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210414T150845Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{AF32C98B-C828-42AF-A649-74C1DE3303FB}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7c52977a-feab-4761-956e-1be4c27281de"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210419T091244Z
